function [ letter_matrix ] = os_letter_matrix( )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here


letter_matrix = {...
    'SV','SW','SX','SY','SZ','TV','TW';...
    'SQ','SR','SS','ST','SU','TQ','TR';...
    'SL','SM','SN','SO','SP','TL','TM';...
    'SF','SG','SH','SJ','SK','TF','TG';...
    'SA','SB','SC','SD','SE','TA','TB';...
    'NV','NW','NX','NY','NZ','OV','OW';...
    'NQ','NR','NS','NT','NU','OQ','OR';...
    'NL','NM','NN','NO','NP','OL','OM';...
    'NF','NG','NH','NJ','NK','OF','OG';...
    'NA','NB','NC','ND','NE','OA','OB';...
    'HV','HW','HX','HY','HZ','JV','JW';...
    'HQ','HR','HS','HT','HU','JQ','JR';...
    'HL','HM','HN','HO','HP','JL','JM'};

end

